on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: MarcoBomfim/gha-brownbag/async@main
        with:
          token: ${{ secrets.MARCO_PAT }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
